version: '3.8'

services:
  app:
    build: ./server
    container_name: flask_app
    ports:
      - "5000:5000"
    depends_on:
      - kafka
      - redis
    volumes:
      - ./tmp:/tmp

  kafka:
    image: wurstmeister/kafka:latest
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    depends_on:
      - zookeeper

  zookeeper:
    image: wurstmeister/zookeeper:latest
    container_name: zookeeper
    ports:
      - "2181:2181"

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"

  consumer:
    build:
      context: ./server
      dockerfile: Dockerfile.consumer
    container_name: kafka_consumer
    depends_on:
      - kafka
      - redis
    volumes:
      - ./tmp:/tmp
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    runtime: nvidia
