# NVIDIA's PyTorch image as the base image
FROM nvcr.io/nvidia/pytorch:22.06-py3

WORKDIR /app

COPY requirements.txt requirements.txt
RUN pip install -r requirements.txt

COPY . .

CMD ["python", "consumer.py"]